services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins-lts
    volumes:
      - "D:/I4/jenkins_home:/var/jenkins_home"
    links:
      - "db:database"
      - "agent1"

  db:
    image: mysql:latest
    user: root
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - "D:/I4/mysql:/var/lib/mysql"

  agent1:
    build: ./laravel-agent
    image: i4a/laravel-agent:latest
    container_name: jenkins-laravel-agent-i4a

    


